### Criar grafico com uma base de dados csv

In [1]:
# passo 1 : importar as bibliotecas e a base de dados 

import pandas as pd
import plotly.express as px

tabela = pd.read_csv('arquivo.csv')

In [2]:
# passo 2 : analisar e remover dados que nao são uteis 
display(tabela)

# osdados inuteis : id_cliente ,  o id não influencia na satisfação do cliente 

tabela.drop(columns='id_cliente')
display(tabela)

,id_cliente,data_adesao,tempo_cliente_meses,cidade,idade,genero,tipo_plano,gasto_mensal_medio,suporte_contatos_ult_6m,reclama_ult_6m,ofertas_recebidas_ult_6m,satisfacao_pesquisa,status_churn
0,1,2023-01-10,29,São Paulo,35,Feminino,Premium,150.0,1.0,Não,5.0,4.0,Não Churn
1,2,2024-03-01,16,Rio de Janeiro,42,Masculino,Básico,70.0,3.0,Sim,2.0,2.0,Churn
2,3,2023-05-15,25,Belo Horizonte,28,Feminino,Padrão,100.0,0.0,Não,4.0,5.0,Não Churn
3,4,2023-08-20,22,Porto Alegre,50,Masculino,Premium,180.0,2.0,Não,6.0,4.0,Não Churn
4,5,2024-01-01,18,Curitiba,30,Feminino,Básico,65.0,4.0,Sim,1.0,1.0,Churn
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,268,2024-06-25,13,Rio de Janeiro,56,Masculino,Padrão,103.0,2.0,Sim,1.0,2.0,Churn
268,269,2023-06-25,24,Belo Horizonte,65,Feminino,Básico,93.0,0.0,Não,3.0,3.0,Não Churn
269,270,2024-07-25,12,Porto Alegre,44,Masculino,Básico,57.0,6.0,Sim,0.0,1.0,Churn
270,271,2023-01-20,29,São Paulo,53,Masculino,Premium,169.0,0.0,Não,5.0,5.0,Não Churn
271,272,2024-03-22,16,Rio de Janeiro,60,Feminino,Básico,89.0,NaN,NaN,NaN,NaN,NaN

,id_cliente,data_adesao,tempo_cliente_meses,cidade,idade,genero,tipo_plano,gasto_mensal_medio,suporte_contatos_ult_6m,reclama_ult_6m,ofertas_recebidas_ult_6m,satisfacao_pesquisa,status_churn
0,1,2023-01-10,29,São Paulo,35,Feminino,Premium,150.0,1.0,Não,5.0,4.0,Não Churn
1,2,2024-03-01,16,Rio de Janeiro,42,Masculino,Básico,70.0,3.0,Sim,2.0,2.0,Churn
2,3,2023-05-15,25,Belo Horizonte,28,Feminino,Padrão,100.0,0.0,Não,4.0,5.0,Não Churn
3,4,2023-08-20,22,Porto Alegre,50,Masculino,Premium,180.0,2.0,Não,6.0,4.0,Não Churn
4,5,2024-01-01,18,Curitiba,30,Feminino,Básico,65.0,4.0,Sim,1.0,1.0,Churn
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,268,2024-06-25,13,Rio de Janeiro,56,Masculino,Padrão,103.0,2.0,Sim,1.0,2.0,Churn
268,269,2023-06-25,24,Belo Horizonte,65,Feminino,Básico,93.0,0.0,Não,3.0,3.0,Não Churn
269,270,2024-07-25,12,Porto Alegre,44,Masculino,Básico,57.0,6.0,Sim,0.0,1.0,Churn
270,271,2023-01-20,29,São Paulo,53,Masculino,Premium,169.0,0.0,Não,5.0,5.0,Não Churn
271,272,2024-03-22,16,Rio de Janeiro,60,Feminino,Básico,89.0,NaN,NaN,NaN,NaN,NaN

In [3]:
# passo 3 : criar os graficos 
for coluna in tabela.columns:

    grafico = px.histogram(tabela, x=coluna, color='status_churn')
    # churn é uma metrica de porcentagem de clientes que deixaram de usar os produtos, ou servisos , de uma empresa em um determinado periodo

    # exibir o grafico

    grafico.show()